export const actionTypes = {
  ADD_ITEM: "ADD_ITEM",
  COMPLETE_ITEM: "COMPLETE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  GET_WEATHER: "GET_WEATHER",
  GET_WEATHER_SUCCESS: "WEATHER_CALL_SUCCESS",
  GET_WEATHER_ERROR: "WEATHER_CALL_FAIL"
};
